# Generated by Django 5.2.16 on 2026-08-03 18:01

import apps.core.storage
import apps.core.validators
import apps.listings.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_brokerage_agentprofile_brandkit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='street address')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city or suburb')),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='state or region')),
                ('postcode', models.CharField(blank=True, max_length=20, verbose_name='postcode')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='country')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='price')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='bedrooms')),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, help_text='Halves are allowed, e.g. 2.5.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='bathrooms')),
                ('square_footage', models.PositiveIntegerField(blank=True, null=True, verbose_name='square footage')),
                ('property_type', models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('townhouse', 'Townhouse'), ('condo', 'Condo'), ('duplex', 'Duplex'), ('land', 'Land'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=32, verbose_name='property type')),
                ('features', models.JSONField(blank=True, default=list, validators=[apps.listings.models.validate_features], verbose_name='features')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_offer', 'Under offer'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=32, verbose_name='listing status')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], db_index=True, default='unverified', max_length=32, verbose_name='verification status')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('import', 'Imported from URL')], default='manual', max_length=16, verbose_name='source')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='source URL')),
                ('imported_fields', models.JSONField(blank=True, default=list, help_text='Names of the fields an import actually populated. Anything not listed here was left blank rather than guessed.', verbose_name='imported fields')),
                ('import_warnings', models.JSONField(blank=True, default=list, help_text='Human-readable notes about what an import could not extract.', verbose_name='import warnings')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.agentprofile', verbose_name='agent')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_listings', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to=apps.core.storage.listing_photo_upload_to, validators=[apps.core.validators.ImageUploadValidator()], verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='source URL')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing', verbose_name='listing')),
            ],
            options={
                'verbose_name': 'listing photo',
                'verbose_name_plural': 'listing photos',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['agent', 'verification_status'], name='listings_li_agent_i_f647fb_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'verification_status'], name='listings_li_status_dea2dc_idx'),
        ),
    ]
