# Generated by Django 5.2.17 on 2026-08-05 17:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_brokerage_agentprofile_brandkit'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='listing',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True, verbose_name='public slug'),
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived'), ('spam', 'Spam')], db_index=True, default='new', max_length=16, verbose_name='status')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='user agent')),
                ('spam_reasons', models.JSONField(blank=True, default=list, verbose_name='spam reasons')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='accounts.agentprofile', verbose_name='agent')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='listings.listing', verbose_name='listing')),
            ],
            options={
                'verbose_name': 'enquiry',
                'verbose_name_plural': 'enquiries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['agent', '-created_at'], name='listings_en_agent_i_2c531c_idx'), models.Index(fields=['listing', '-created_at'], name='listings_en_listing_567ced_idx'), models.Index(fields=['status', '-created_at'], name='listings_en_status_564a77_idx')],
            },
        ),
    ]
