# Generated by Django 5.2.16 on 2026-08-03 17:27

import apps.core.storage
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brokerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.core.storage.brokerage_logo_upload_to, validators=[apps.core.validators.ImageUploadValidator()], verbose_name='logo')),
                ('required_disclaimer', models.TextField(blank=True, help_text='Regulatory text that must appear on marketing material produced for this brokerage.', verbose_name='required disclaimer')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('admins', models.ManyToManyField(blank=True, help_text='Users who may manage this brokerage and its agents. Assigning an administrator does not by itself change their role.', related_name='administered_brokerages', to=settings.AUTH_USER_MODEL, verbose_name='administrators')),
            ],
            options={
                'verbose_name': 'brokerage',
                'verbose_name_plural': 'brokerages',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='display name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.core.storage.agent_photo_upload_to, validators=[apps.core.validators.ImageUploadValidator()], verbose_name='photo')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='public email')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='job title')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='tagline')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('brokerage', models.ForeignKey(blank=True, help_text="Losing a brokerage must not delete an agent's profile, hence SET_NULL rather than CASCADE.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='accounts.brokerage', verbose_name='brokerage')),
            ],
            options={
                'verbose_name': 'agent profile',
                'verbose_name_plural': 'agent profiles',
                'ordering': ('name', 'user__email'),
            },
        ),
        migrations.CreateModel(
            name='BrandKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='name')),
                ('primary_color', models.CharField(default='#1F2937', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a hex colour such as #1F2937 or #FFF.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='primary colour')),
                ('secondary_color', models.CharField(default='#4B5563', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a hex colour such as #1F2937 or #FFF.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='secondary colour')),
                ('accent_color', models.CharField(default='#2563EB', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a hex colour such as #1F2937 or #FFF.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='accent colour')),
                ('heading_font', models.CharField(default='Inter', max_length=120, verbose_name='heading font')),
                ('body_font', models.CharField(default='Inter', max_length=120, verbose_name='body font')),
                ('design_style', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('luxury', 'Luxury'), ('warm', 'Warm')], default='modern', max_length=32, verbose_name='preferred design style')),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_kit', to='accounts.agentprofile', verbose_name='agent')),
                ('brokerage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_kit', to='accounts.brokerage', verbose_name='brokerage')),
            ],
            options={
                'verbose_name': 'brand kit',
                'verbose_name_plural': 'brand kits',
                'ordering': ('-updated_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', False), ('brokerage__isnull', True)), models.Q(('agent__isnull', True), ('brokerage__isnull', False)), _connector='OR'), name='brandkit_belongs_to_exactly_one_owner')],
            },
        ),
    ]
