# Generated by Django 5.2.17 on 2026-08-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_brokerage_agentprofile_brandkit'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='licence_number',
            field=models.CharField(blank=True, help_text='Agent licence or registration number, where required.', max_length=64, verbose_name='licence number'),
        ),
        migrations.AddField(
            model_name='brokerage',
            name='licence_number',
            field=models.CharField(blank=True, help_text='Brokerage licence or registration number, where required.', max_length=64, verbose_name='licence number'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Derived from first and last name when those are set.', max_length=255, verbose_name='full name'),
        ),
    ]
