# Generated by Django 5.2.16 on 2026-08-04 15:35

import apps.core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_brokerage_agentprofile_brandkit'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=160, verbose_name='name')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(choices=[('new_listing', 'New Listing'), ('coming_soon', 'Coming Soon'), ('open_house', 'Open House'), ('just_sold', 'Just Sold'), ('price_reduced', 'Price Reduced'), ('leased', 'Leased'), ('agent_introduction', 'Agent Introduction'), ('testimonial', 'Testimonial'), ('market_update', 'Market Update'), ('neighbourhood_guide', 'Neighbourhood Guide')], db_index=True, max_length=32, verbose_name='category')),
                ('style', models.CharField(choices=[('bold', 'Bold'), ('minimal', 'Minimal'), ('luxury', 'Luxury'), ('warm', 'Warm'), ('editorial', 'Editorial'), ('classic', 'Classic')], db_index=True, max_length=32, verbose_name='style')),
                ('layout_definition', models.JSONField(blank=True, default=dict, help_text='Canvas-level settings: base aspect ratio, background, padding. Element geometry lives on TemplateElement.', verbose_name='layout definition')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'ordering': ('category', 'style', 'name'),
                'indexes': [models.Index(fields=['category', 'style', 'is_active'], name='templates_t_categor_0d395d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=160, verbose_name='name')),
                ('overrides', models.JSONField(blank=True, default=dict, help_text="{element_key: {field: value}}. Validated against each element's permission and constraints before it is ever stored.", verbose_name='overrides')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='accounts.agentprofile')),
                ('listing', models.ForeignKey(blank=True, help_text='Optional: agent-introduction and market-update templates need no listing. When set, it must be a verified listing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='listings.listing')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='templates.template')),
            ],
            options={
                'verbose_name': 'design',
                'verbose_name_plural': 'designs',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='TemplateElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, verbose_name='key')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='label')),
                ('element_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('color_block', 'Colour block'), ('logo', 'Logo'), ('badge', 'Badge'), ('divider', 'Divider')], max_length=32, verbose_name='element type')),
                ('permission', models.CharField(choices=[('locked', 'Locked — no changes'), ('content_only', 'Content only — swap text or image'), ('styled', 'Styled — content plus limited colour and size'), ('free', 'Free — move, resize and restyle within bounds')], default='locked', help_text='Locked by default: an element is not editable unless it says so.', max_length=32, verbose_name='permission')),
                ('geometry', models.JSONField(default=dict, verbose_name='geometry')),
                ('style_properties', models.JSONField(blank=True, default=dict, verbose_name='style properties')),
                ('content_source', models.CharField(blank=True, max_length=120, verbose_name='content source')),
                ('default_content', models.TextField(blank=True, verbose_name='default content')),
                ('constraints', models.JSONField(blank=True, default=dict, help_text='Limits applied to overrides: allowed_colors, min/max font size ratio, bounds for movement, max_length for text.', verbose_name='constraints')),
                ('z_index', models.PositiveIntegerField(default=0, verbose_name='z-index')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='templates.template')),
            ],
            options={
                'verbose_name': 'template element',
                'verbose_name_plural': 'template elements',
                'ordering': ('z_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DesignExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('dimension', models.CharField(db_index=True, max_length=40, verbose_name='dimension')),
                ('export_format', models.CharField(choices=[('png', 'PNG'), ('jpg', 'JPG')], default='png', max_length=8, verbose_name='format')),
                ('image', models.ImageField(upload_to=apps.core.storage.design_export_upload_to, verbose_name='image')),
                ('width', models.PositiveIntegerField(verbose_name='width')),
                ('height', models.PositiveIntegerField(verbose_name='height')),
                ('bytes', models.PositiveIntegerField(default=0, verbose_name='bytes')),
                ('render_ms', models.PositiveIntegerField(default=0, verbose_name='render time (ms)')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='templates.design')),
            ],
            options={
                'verbose_name': 'design export',
                'verbose_name_plural': 'design exports',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['design', 'dimension', 'export_format'], name='templates_d_design__c4c99a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['agent', '-updated_at'], name='templates_d_agent_i_6a8d90_idx'),
        ),
        migrations.AddConstraint(
            model_name='templateelement',
            constraint=models.UniqueConstraint(fields=('template', 'key'), name='unique_element_key_per_template'),
        ),
    ]
