# Generated by Django 5.2.17 on 2026-08-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_backfill_public_slug'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='Optional: agent-introduction, market-update and seasonal templates need no listing. When set, it must be a verified listing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('new_listing', 'New Listing'), ('coming_soon', 'Coming Soon'), ('open_house', 'Open House'), ('just_sold', 'Just Sold'), ('price_reduced', 'Price Reduced'), ('leased', 'Leased'), ('agent_introduction', 'Agent Introduction'), ('testimonial', 'Testimonial'), ('market_update', 'Market Update'), ('neighbourhood_guide', 'Neighbourhood Guide'), ('christmas', 'Christmas'), ('new_year', 'New Year'), ('lunar_new_year', 'Lunar New Year'), ('diwali', 'Diwali'), ('eid', 'Eid'), ('hanukkah', 'Hanukkah'), ('easter', 'Easter'), ('thanksgiving', 'Thanksgiving'), ('canada_day', 'Canada Day'), ('australia_day', 'Australia Day'), ('mothers_day', "Mother's Day"), ('fathers_day', "Father's Day"), ('seasonal', 'Seasonal (general)')], db_index=True, max_length=32, verbose_name='category'),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, verbose_name='slug')),
                ('category', models.CharField(choices=[('new_listing', 'New Listing'), ('coming_soon', 'Coming Soon'), ('open_house', 'Open House'), ('just_sold', 'Just Sold'), ('price_reduced', 'Price Reduced'), ('leased', 'Leased'), ('agent_introduction', 'Agent Introduction'), ('testimonial', 'Testimonial'), ('market_update', 'Market Update'), ('neighbourhood_guide', 'Neighbourhood Guide'), ('christmas', 'Christmas'), ('new_year', 'New Year'), ('lunar_new_year', 'Lunar New Year'), ('diwali', 'Diwali'), ('eid', 'Eid'), ('hanukkah', 'Hanukkah'), ('easter', 'Easter'), ('thanksgiving', 'Thanksgiving'), ('canada_day', 'Canada Day'), ('australia_day', 'Australia Day'), ('mothers_day', "Mother's Day"), ('fathers_day', "Father's Day"), ('seasonal', 'Seasonal (general)')], db_index=True, help_text='Which templates this event surfaces.', max_length=32, verbose_name='template category')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('regions', models.JSONField(blank=True, default=list, verbose_name='regions')),
                ('needs_date_review', models.BooleanField(default=False, help_text='Set for events on lunar or lunisolar calendars, whose dates cannot be extrapolated and must be confirmed each year.', verbose_name='date needs review')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'calendar event',
                'verbose_name_plural': 'calendar events',
                'ordering': ('date', 'name'),
                'indexes': [models.Index(fields=['date', 'is_active'], name='templates_c_date_23baeb_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'date'), name='unique_calendar_event_occurrence')],
            },
        ),
        migrations.AddField(
            model_name='design',
            name='calendar_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='templates.calendarevent'),
        ),
    ]
