# Generated by Django 5.2.17 on 2026-08-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_alter_design_listing_alter_template_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='needs_date_review',
            field=models.BooleanField(default=False, help_text="Set for any event whose date is not fixed — lunar and lunisolar festivals, and nth-weekday holidays like Thanksgiving. None of them are calculated here, so each year's date must be confirmed.", verbose_name='date needs review'),
        ),
    ]
