# Generated by Django 5.2.17 on 2026-08-11 05:25

import apps.core.storage
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_alter_calendarevent_needs_date_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateelement',
            name='static_asset',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.storage.template_asset_upload_to, validators=[apps.core.validators.ImageUploadValidator()], verbose_name='static asset'),
        ),
        migrations.AlterField(
            model_name='templateelement',
            name='element_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('color_block', 'Colour block'), ('logo', 'Logo'), ('badge', 'Badge'), ('divider', 'Divider'), ('static_graphic', 'Static graphic')], max_length=32, verbose_name='element type'),
        ),
    ]
