# Generated by Django 5.2.17 on 2026-08-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_templateelement_static_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='extra_elements',
            field=models.JSONField(blank=True, default=list, verbose_name='extra elements'),
        ),
    ]
