# Generated by Django 5.2.17 on 2026-08-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_design_extra_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designexport',
            name='export_format',
            field=models.CharField(choices=[('png', 'PNG'), ('jpg', 'JPG'), ('pdf', 'PDF')], default='png', max_length=8, verbose_name='format'),
        ),
    ]
