# Generated by Django 5.2.17 on 2026-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_alter_designexport_export_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='allows_added_elements',
            field=models.BooleanField(default=True, help_text='Whether agents may add their own text, images and shapes to a design made from this template. Turn off for layouts that must stay exactly as designed — element-level permissions still apply either way.', verbose_name='allows added elements'),
        ),
    ]
