# Generated by Django 5.2.17 on 2026-08-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0007_template_allows_added_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='default_dimension',
            field=models.CharField(default='instagram_post', help_text='The format this template was composed for — the one the editor opens. Geometry is normalised so every template still renders at every size, but a layout drawn tall reads as a crop when opened square, so it should not open square.', max_length=40, verbose_name='native format'),
        ),
    ]
