# Generated by Django 5.2.17 on 2026-08-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0009_design_elements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateelement',
            name='constraints',
        ),
        migrations.AlterField(
            model_name='template',
            name='allows_added_elements',
            field=models.BooleanField(default=True, help_text="Whether the editor offers to add new elements to a design made from this template. A hint about how the layout is meant to be used — not a restriction on the elements it already has, which are the agent's to change once the design exists.", verbose_name='allows added elements'),
        ),
    ]
