# Generated by Django 5.2.17 on 2026-08-14 02:13

import apps.core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agentprofile_licence_number_brokerage_licence_number_and_more'),
        ('templates', '0010_drop_element_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source_file', models.FileField(upload_to=apps.core.storage.template_import_upload_to, verbose_name='source file')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='original filename')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16, verbose_name='status')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('requested_name', models.CharField(blank=True, max_length=160, verbose_name='requested name')),
                ('category', models.CharField(choices=[('new_listing', 'New Listing'), ('coming_soon', 'Coming Soon'), ('open_house', 'Open House'), ('just_sold', 'Just Sold'), ('price_reduced', 'Price Reduced'), ('leased', 'Leased'), ('agent_introduction', 'Agent Introduction'), ('testimonial', 'Testimonial'), ('market_update', 'Market Update'), ('neighbourhood_guide', 'Neighbourhood Guide'), ('christmas', 'Christmas'), ('new_year', 'New Year'), ('lunar_new_year', 'Lunar New Year'), ('diwali', 'Diwali'), ('eid', 'Eid'), ('hanukkah', 'Hanukkah'), ('easter', 'Easter'), ('thanksgiving', 'Thanksgiving'), ('canada_day', 'Canada Day'), ('australia_day', 'Australia Day'), ('mothers_day', "Mother's Day"), ('fathers_day', "Father's Day"), ('seasonal', 'Seasonal (general)')], default='new_listing', max_length=32, verbose_name='category')),
                ('style', models.CharField(choices=[('bold', 'Bold'), ('minimal', 'Minimal'), ('luxury', 'Luxury'), ('warm', 'Warm'), ('editorial', 'Editorial'), ('classic', 'Classic')], default='minimal', max_length=32, verbose_name='style')),
                ('element_count', models.PositiveIntegerField(default=0, verbose_name='elements found')),
                ('model_used', models.CharField(blank=True, max_length=80, verbose_name='model')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='prompt tokens')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='completion tokens')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='duration (ms)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
            ],
            options={
                'verbose_name': 'template import',
                'verbose_name_plural': 'template imports',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The agent who imported this template. Blank for the shared Nehrux library, which every agent can see.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='accounts.agentprofile', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='template',
            name='source_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.storage.template_source_page_upload_to, verbose_name='source artwork'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['owner', 'is_active'], name='templates_t_owner_i_38c08e_idx'),
        ),
        migrations.AddField(
            model_name='templateimport',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_imports', to='accounts.agentprofile', verbose_name='agent'),
        ),
        migrations.AddField(
            model_name='templateimport',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='templates.template', verbose_name='template'),
        ),
        migrations.AddIndex(
            model_name='templateimport',
            index=models.Index(fields=['agent', '-created_at'], name='templates_t_agent_i_98af53_idx'),
        ),
    ]
