# Generated by Django 5.2.17 on 2026-08-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0011_templateimport_template_owner_template_source_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='preferred_dimension',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='preferred format'),
        ),
    ]
