# Generated by Django 5.2.17 on 2026-08-05 14:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('kind', models.CharField(choices=[('social_caption', 'Social caption and hashtags')], default='social_caption', max_length=32, verbose_name='kind')),
                ('job_status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16, verbose_name='job status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('caption', models.TextField(blank=True, verbose_name='caption')),
                ('hashtags', models.JSONField(blank=True, default=list, verbose_name='hashtags')),
                ('rejected_output', models.JSONField(blank=True, default=dict, verbose_name='rejected output')),
                ('validation_status', models.CharField(choices=[('pending', 'Not yet validated'), ('passed', 'Passed'), ('flagged', 'Passed with warnings'), ('rejected', 'Rejected — unverifiable claims')], db_index=True, default='pending', max_length=16, verbose_name='validation status')),
                ('validation_issues', models.JSONField(blank=True, default=list, verbose_name='validation issues')),
                ('review_status', models.CharField(choices=[('draft', 'Draft — awaiting agent review'), ('approved', 'Approved by agent'), ('rejected', 'Rejected by agent')], db_index=True, default='draft', max_length=16, verbose_name='review status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('model_name', models.CharField(blank=True, max_length=80, verbose_name='model')),
                ('prompt_version', models.CharField(blank=True, max_length=20, verbose_name='prompt version')),
                ('prompt_facts', models.JSONField(blank=True, default=dict, verbose_name='prompt facts')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='prompt tokens')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='completion tokens')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='total tokens')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10, verbose_name='estimated cost (USD)')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='duration (ms)')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to='listings.listing', verbose_name='listing')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_generations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'generated content',
                'verbose_name_plural': 'generated content',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['listing', '-created_at'], name='ai_content__listing_9f1433_idx'), models.Index(fields=['job_status', '-created_at'], name='ai_content__job_sta_90512e_idx')],
            },
        ),
    ]
