# Generated by Django 5.2.17 on 2026-08-05 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='kind',
            field=models.CharField(choices=[('social_caption', 'Social caption and hashtags'), ('content_pack', 'Full content pack')], default='social_caption', max_length=32, verbose_name='kind'),
        ),
        migrations.CreateModel(
            name='ContentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('kind', models.CharField(choices=[('instagram_caption', 'Instagram caption'), ('facebook_caption', 'Facebook caption'), ('linkedin_caption', 'LinkedIn caption'), ('sharing_message', 'Sharing message'), ('property_description', 'Property page description'), ('hashtags', 'Hashtags')], max_length=32, verbose_name='kind')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='items')),
                ('rejected_text', models.TextField(blank=True, verbose_name='rejected text')),
                ('rejected_items', models.JSONField(blank=True, default=list, verbose_name='rejected items')),
                ('validation_status', models.CharField(choices=[('pending', 'Not yet validated'), ('passed', 'Passed'), ('flagged', 'Passed with warnings'), ('rejected', 'Rejected — unverifiable claims')], db_index=True, default='pending', max_length=16, verbose_name='validation status')),
                ('validation_issues', models.JSONField(blank=True, default=list, verbose_name='validation issues')),
                ('review_status', models.CharField(choices=[('draft', 'Draft — awaiting agent review'), ('approved', 'Approved by agent'), ('rejected', 'Rejected by agent')], db_index=True, default='draft', max_length=16, verbose_name='review status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('is_edited', models.BooleanField(default=False, verbose_name='edited by agent')),
                ('original_text', models.TextField(blank=True, verbose_name='original text')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ai_content.generatedcontent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_variants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'content variant',
                'verbose_name_plural': 'content variants',
                'ordering': ('generation_id', 'id'),
                'indexes': [models.Index(fields=['generation', 'kind'], name='ai_content__generat_dc65fc_idx')],
                'constraints': [models.UniqueConstraint(fields=('generation', 'kind'), name='unique_variant_kind_per_generation')],
            },
        ),
    ]
