# Generated by Django 5.2.17 on 2026-08-06 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_content', '0002_alter_generatedcontent_kind_contentvariant'),
        ('listings', '0003_backfill_public_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=16, verbose_name='language'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['listing', 'language', '-created_at'], name='ai_content__listing_88a1f6_idx'),
        ),
    ]
