# Generated by Django 5.2.17 on 2026-08-05 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_brokerage_agentprofile_brandkit'),
        ('ai_content', '0002_alter_generatedcontent_kind_contentvariant'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('subject_kind', models.CharField(max_length=32, verbose_name='subject kind')),
                ('subject_label', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('flagged', 'Passed with warnings'), ('failed', 'Failed')], db_index=True, max_length=16, verbose_name='status')),
                ('results', models.JSONField(blank=True, default=list, verbose_name='results')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='errors')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='warnings')),
                ('used_placeholder_rules', models.BooleanField(default=True)),
                ('content_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_evaluations', to='ai_content.contentvariant')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_evaluations', to='templates.design')),
                ('generated_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_evaluations', to='ai_content.generatedcontent')),
            ],
            options={
                'verbose_name': 'compliance evaluation',
                'verbose_name_plural': 'compliance evaluations',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='compliance__status_68042a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('rule_id', models.SlugField(help_text='Stable identifier used in reports and audit trails. Do not reuse an id for a different requirement — supersede it and add a new one.', max_length=80, unique=True, verbose_name='rule id')),
                ('description', models.CharField(help_text='Shown to the agent when this rule fails. Write it as advice.', max_length=255, verbose_name='description')),
                ('check_type', models.CharField(choices=[('required_field_present', 'Required field present'), ('disclaimer_present', 'Disclaimer present'), ('prohibited_phrase', 'Prohibited phrase'), ('required_phrase', 'Required phrase'), ('prohibited_pattern', 'Prohibited pattern (regex)'), ('length_limit', 'Length limit'), ('custom', 'Custom (registered handler)')], db_index=True, max_length=40, verbose_name='check type')),
                ('rule_data', models.JSONField(blank=True, default=dict, help_text='The specifics. The shape depends on the check type.', verbose_name='rule data')),
                ('severity', models.CharField(choices=[('error', 'Error — blocks export'), ('warning', 'Warning — shown, does not block'), ('info', 'Info — advisory only')], default='warning', max_length=16, verbose_name='severity')),
                ('applies_to', models.CharField(choices=[('all', 'All content'), ('ai_content', 'AI-generated content'), ('design', 'Designs and exports'), ('listing', 'Listings')], default='all', max_length=24, verbose_name='applies to')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to stop applying this rule without deleting it.', verbose_name='active')),
                ('legal_status', models.CharField(choices=[('pending_review', 'PENDING LEGAL REVIEW — placeholder'), ('approved', 'Approved'), ('superseded', 'Superseded')], db_index=True, default='pending_review', help_text='Rules ship as PENDING LEGAL REVIEW. Only set this to Approved if you have the authority to sign the wording off.', max_length=24, verbose_name='legal status')),
                ('admin_notes', models.TextField(blank=True, help_text='Provenance, source of the requirement, review history.', verbose_name='notes')),
                ('order', models.PositiveIntegerField(default=100, help_text='Lower numbers are reported first.', verbose_name='order')),
                ('brokerage', models.ForeignKey(blank=True, help_text='Leave blank for a rule that applies to every brokerage.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_rules', to='accounts.brokerage', verbose_name='brokerage')),
            ],
            options={
                'verbose_name': 'compliance rule',
                'verbose_name_plural': 'compliance rules',
                'ordering': ('order', 'rule_id'),
                'indexes': [models.Index(fields=['is_active', 'applies_to'], name='compliance__is_acti_80f9f7_idx')],
            },
        ),
    ]
